import { CoffeCategory, type CoffeItemProps } from '../model/Coffe'

export const data: CoffeItemProps[] = [
  {
    id: '1',
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    img: '/src/assets/expresso.png',
    price: 9.9,
    categories: [CoffeCategory.TRADICIONAL],
  },
  {
    id: '2',
    name: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    img: '/src/assets/americano.png',
    price: 9.9,
    categories: [CoffeCategory.TRADICIONAL],
  },
  {
    id: '3',
    name: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    img: '/src/assets/expresso-cremoso.png',
    price: 9.9,
    categories: [CoffeCategory.TRADICIONAL],
  },
  {
    id: '4',
    name: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    img: '/src/assets/cafe-gelado.png',
    price: 9.9,
    categories: [CoffeCategory.TRADICIONAL, CoffeCategory.GEALDO],
  },
  {
    id: '5',
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    img: '/src/assets/expresso.png',
    price: 9.9,
    categories: [CoffeCategory.TRADICIONAL],
  },
  {
    id: '6',
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    img: '/src/assets/expresso.png',
    price: 9.9,
    categories: [CoffeCategory.TRADICIONAL],
  },
  {
    id: '7',
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    img: '/src/assets/expresso.png',
    price: 9.9,
    categories: [CoffeCategory.TRADICIONAL],
  },
  {
    id: '8',
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    img: '/src/assets/expresso.png',
    price: 9.9,
    categories: [CoffeCategory.TRADICIONAL],
  },
  {
    id: '5',
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    img: '/src/assets/expresso.png',
    price: 9.9,
    categories: [CoffeCategory.TRADICIONAL],
  },
  {
    id: '6',
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    img: '/src/assets/expresso.png',
    price: 9.9,
    categories: [CoffeCategory.TRADICIONAL],
  },
  {
    id: '7',
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    img: '/src/assets/expresso.png',
    price: 9.9,
    categories: [CoffeCategory.TRADICIONAL],
  },
  {
    id: '8',
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    img: '/src/assets/expresso.png',
    price: 9.9,
    categories: [CoffeCategory.TRADICIONAL],
  },
  {
    id: '7',
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    img: '/src/assets/expresso.png',
    price: 9.9,
    categories: [CoffeCategory.TRADICIONAL],
  },
  {
    id: '8',
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    img: '/src/assets/expresso.png',
    price: 9.9,
    categories: [CoffeCategory.TRADICIONAL],
  },
]
