import { CoffeCategory, type CoffeItemProps } from '../model/Coffe'

export const data: CoffeItemProps[] = [
  {
    id: '1',
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    img: '/src/assets/expresso.png',
    price: 9.9,
    categories: [CoffeCategory.TRADICIONAL],
  },
  {
    id: '2',
    name: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    img: '/src/assets/americano.png',
    price: 9.9,
    categories: [CoffeCategory.TRADICIONAL],
  },
  {
    id: '3',
    name: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    img: '/src/assets/expresso-cremoso.png',
    price: 9.9,
    categories: [CoffeCategory.TRADICIONAL],
  },
  {
    id: '4',
    name: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    img: '/src/assets/cafe-gelado.png',
    price: 9.9,
    categories: [CoffeCategory.TRADICIONAL, CoffeCategory.GELADO],
  },
  {
    id: '5',
    name: 'café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    img: '/src/assets/cafe-com-leite.png',
    price: 9.9,
    categories: [CoffeCategory.TRADICIONAL, CoffeCategory.COM_LEITE],
  },
  {
    id: '6',
    name: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    img: '/src/assets/latte.png',
    price: 9.9,
    categories: [CoffeCategory.TRADICIONAL, CoffeCategory.COM_LEITE],
  },
  {
    id: '7',
    name: 'Capuccino',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    img: '/src/assets/capuccino.png',
    price: 9.9,
    categories: [CoffeCategory.TRADICIONAL, CoffeCategory.COM_LEITE],
  },
  {
    id: '8',
    name: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    img: '/src/assets/macchiato.png',
    price: 9.9,
    categories: [CoffeCategory.TRADICIONAL, CoffeCategory.COM_LEITE],
  },
  {
    id: '9',
    name: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    img: '/src/assets/mochaccino.png',
    price: 9.9,
    categories: [CoffeCategory.TRADICIONAL, CoffeCategory.COM_LEITE],
  },
  {
    id: '10',
    name: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    img: '/src/assets/chocolate-quente.png',
    price: 9.9,
    categories: [CoffeCategory.ESPECIAL, CoffeCategory.COM_LEITE],
  },
  {
    id: '11',
    name: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    img: '/src/assets/cubano.png',
    price: 9.9,
    categories: [
      CoffeCategory.ESPECIAL,
      CoffeCategory.ALCOOLICO,
      CoffeCategory.GELADO,
    ],
  },
  {
    id: '12',
    name: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    img: '/src/assets/havaiano.png',
    price: 9.9,
    categories: [CoffeCategory.ESPECIAL],
  },
  {
    id: '13',
    name: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    img: '/src/assets/arabe.png',
    price: 9.9,
    categories: [CoffeCategory.ESPECIAL],
  },
  {
    id: '14',
    name: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    img: '/src/assets/irlandes.png',
    price: 9.9,
    categories: [CoffeCategory.ESPECIAL, CoffeCategory.ALCOOLICO],
  },
]
